### ISSUE TITLE
CGAccount - isCorrectPassword() method checks only first keystore

### ISSUE THREAD

**Issue by irubido** [NodeFactoryIo/ChainGuardian#135]
Currently login works only for 1 password
Comments in the code:
/**
? As there can be multiple keystore files there can also be
? different passwords that these keystores use, we need to
? define how are we going to handle these situations.
Currently, if any of the keystores matches the provided
password this method returns true.
*/

/**
Check only first file as we assume that all keystores
have the same password.
*/

**Comment by mpetrunic** [comment]
replaced by #240
