### ISSUE TITLE
Domain should use genesis fork

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/ChainGuardian#200]
Reference: https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/beacon-chain.md#compute_domain

**Comment by morrigan** [comment]
This is part of lodestar lib. We don't use it anywhere in the code, except from the last PR.

**Comment by mpetrunic** [comment]
Yeah, missed that by default it genesis fork version from config
