### ISSUE TITLE
Application crashes if you remove last validator

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/ChainGuardian#227]
App should display empty dashboard with some message and link to add new validator.

**Comment by mpetrunic** [comment]
Or maybe we should redirect to register since add validator flow probably won't work.
We should also keep in mind that user should be able to access beacon nodes even though it doesn't have validators.

I would propose we drop login screen and instead load dashboard immediately where user should enter password to start/stop validator. And dashboard should have link to Beacon nodes screen where user can start/stop BNs

What do you think @morrigan

**Comment by morrigan** [comment]
I agree with redirect to register.

> We should also keep in mind that user should be able to access beacon nodes even though it doesn't have validators.

This is a good point. We can have a separate screen with beacon node list as we have them saved in db anyway. There we can add more start/stop control.

> I would propose we drop login screen and instead load dashboard immediately where user should enter password to start/stop validator.

I don't think that this has much pros really. It's also better for the user that no one can open app and see sensitive info (earnings) without pw.
