### ISSUE TITLE
Beacon node syncing slot not refreshing

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/ChainGuardian#233]
Beacon node card should also indicate network

![image.png](https://images.zenhubusercontent.com/5cd001edd503031def6241c6/ef1c6b94-50d0-4cf4-bf4d-2535ac09f7c6)

**Comment by morrigan** [comment]
Should validator card rather display network?

**Comment by mpetrunic** [comment]
> Should validator card rather display network?

Not sure, validator is not tied to network per se, it's just BN but we can but it on validator card if it makes more sense

**Comment by morrigan** [comment]
I can't reproduce this. Actions displayed in the console should contain new slot height so doesn't make much sense not to render. Is it possible that was BN issue?

**Comment by mpetrunic** [comment]
It should display current headslot and refresh like every 10ish seconds or something

**Comment by morrigan** [comment]
> It should display current headslot and refresh like every 10ish seconds or something

Yep, it's what it does... This redux action is that

**Comment by mpetrunic** [comment]
But I have always same slot, and it's different everytime I start app. I think you should demonstrate this  tommorow

**Comment by morrigan** [comment]
@mpetrunic is this still an issue that can be reproduced?
