### ISSUE TITLE
Beacon node logs missing

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/ChainGuardian#234]
![image.png](https://images.zenhubusercontent.com/5cd001edd503031def6241c6/5cb7aaf5-170b-49f5-b486-8e3048a894da)

**Comment by morrigan** [comment]
This works only when running your own BN Docker.

**Comment by mpetrunic** [comment]
I ran my own BN docker trough Chainguardian

**Comment by morrigan** [comment]
> I ran my own BN docker trough Chainguardian

That should be fine... :/ Maybe it took a bit longer time to load?

**Comment by mpetrunic** [comment]
Not sure, there was plenty of logs when I've queried Bn but Bn ran into errors. Maybe we should buffer logs before we get to that screen so we have something to display (like last 1k lines) and then just add to front and remove from end
