### ISSUE TITLE
EventIterator queue reached Xn items infinity loop

### ISSUE THREAD

**Issue by BeroBurny** [NodeFactoryIo/ChainGuardian#317]
after rerunning the container from BN details logging system get crazy
![Screenshot from 2020-11-25 12-40-29](https://user-images.githubusercontent.com/6376047/100223478-d50db580-2f1b-11eb-8df6-5f9bec90efd8.png)
```
react_devtools_backend.js:2430 EventIterator queue reached 191 items
overrideMethod @ react_devtools_backend.js:2430
push @ event-iterator.js:25
logHandler @ buffered.ts:25
emit @ events.js:310
push @ fifo.ts:17
(anonymous) @ buffered.ts:49
push @ buffered.ts:48
(anonymous) @ buffered.ts:38
emit @ events.js:322
addChunk @ _stream_readable.js:286
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:209
onStreamRead @ internal/stream_base_commons.js:186
```

and after a while crash UI
![Screenshot from 2020-11-25 12-44-39](https://user-images.githubusercontent.com/6376047/100223622-0a1a0800-2f1c-11eb-8bf7-6bc81ac3eedc.png)

@mpetrunic think you got best inside about this logger

**Comment by mpetrunic** [comment]
My best guess it that we are pushing stuff into iterator but unless you are on logger view, we never consumed it. We should probably create some wrapper and consume/clear old logs once we reach certain treshold. I think we can also increase this treshold in EventIterator
