### ISSUE TITLE
Open app as maximized

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/ChainGuardian#37]
- figure out how to open screen in maximized format
- change help menu to contain only "Github repo" and "Search Issues" items
- add chainguardian logo as app icon
- rename window title to ChainGuardian

**Comment by MakMuftic** [comment]
@mpetrunic few remarks on this subtasks (_marked what is finished_):
#### figure out how to open screen in maximized format :heavy_check_mark:
While looking into this subtask I found something interesting and implemented it into the project. It is described in official electron documentation as [Showing windows gracefully](https://electronjs.org/docs/api/browser-window#showing-window-gracefully). I took background color from @irubido so it matches with other visuals.
#### change help menu to contain only "Github repo" and "Search Issues" items :x:
So far it seems that _it is not possible to change the default app menu_ without defining the new menu template. **General practice is to take default menu template code from electron lib, copy/paste it to project and then make changes/additions to template.** All of these basic actions are predefined as roles, so the template is pretty straightforward and looks something like this ( just a snip from template ):

```javascript
{
    label: 'View',
    submenu: [
      { role: 'reload' },
      { role: 'forcereload' },
      { role: 'toggledevtools' },
      { type: 'separator' },
      { role: 'resetzoom' },
      { role: 'zoomin' },
      { role: 'zoomout' },
      { type: 'separator' },
      { role: 'togglefullscreen' }
    ]
  },
```

I will investigate a little bit more this topic just to be sure.
#### add chainguardian logo as app icon :x:
Regarding this subtask, after research, I concluded that the best way to do this and have the same behavior on different platforms is [this solution](https://github.com/electron/electron/issues/6205#issuecomment-362588476). It forces us to use [electron-builder](https://github.com/electron-userland/electron-builder), so please look into it. 

There is an alternative to this, using package.json to define platform-specific icons (_this is the reason why setting icon is complicated, win wants .ico format, macOS something else..._)

Finally, setting an app icon in code is possible but it requires some manual copy/paste when building an app to work properly and it can produce some strange behavior.
#### rename window title to ChainGuardian :heavy_check_mark:
This is a one-liner, but it might be interesting to take the version from _package.json_ and set the window title to something like this: **ChainGuardian 0.0.1**. Not sure this is needed !?

**Comment by mpetrunic** [comment]
everything seems fine. Drop version from window title, we will put it on some corner probably
