### ISSUE TITLE
Docker run in new console on Windows

### ISSUE THREAD

**Issue by morrigan** [NodeFactoryIo/ChainGuardian#409]
Can this run in the background rather than new window?

![konzolaskrinsot](https://user-images.githubusercontent.com/4976604/104109096-a9c40780-52ca-11eb-8162-64f15d11d2f9.png)

**Comment by BeroBurny** [comment]
note: while using `runDetached` from `cmd.ts` shell is open because of option `shell: true`

**Comment by morrigan** [comment]
> note: while using `runDetached` from `cmd.ts` shell is open because of option `shell: true`

I am not sure if we can disable that since we need shell to run the command... Can you check?

**Comment by BeroBurny** [comment]
probably we don't even need to run this as a new process, think `runCmdAsync` should work just fine

**Comment by BeroBurny** [comment]
> probably we don't even need to run this as a new process, think `runCmdAsync` should work just fine

seems this solve a problem on my own testing, need additional confirmation to be sure

**Comment by morrigan** [comment]
Seems to be fixed, running 0.5.2.
