### ISSUE TITLE
Removing last validator allowed but does not work

### ISSUE THREAD

**Issue by morrigan** [NodeFactoryIo/ChainGuardian#415]
I have only 1 validator, can't remove it when I click "confirm"

**Comment by BeroBurny** [comment]
@morrigan cannot reproduce attempt to remove whit attached beacon node and without (even when active) still remove fine (on dev env)

**Comment by morrigan** [comment]
Can't replicate anymore

**Comment by BeroBurny** [comment]
i just reproduce it :see_no_evil:

**Comment by morrigan** [comment]
> i just reproduce it 🙈

How?

**Comment by BeroBurny** [comment]
its error after there is no account yet (fresh install) and if you want to delete validator on fresh install its fails bc of logical error
