### ISSUE TITLE
Failed to fetch validator.

### ISSUE THREAD

**Issue by BeroBurny** [NodeFactoryIo/ChainGuardian#490]
in `renderer.log` there is an error message` Failed to fetch validator` that show us this error is unhandled or error logging is wrongly handled

**Comment by mpetrunic** [comment]
maybe we tried to fetch validator before is was registered on beacon chain (his deposit processed)?

**Comment by BeroBurny** [comment]
> maybe we tried to fetch validator before is was registered on beacon chain (his deposit processed)?

probably is but still, this should be shown as an error, and `renderer.log` shows unhandled log's

**Comment by morrigan** [comment]
> > maybe we tried to fetch validator before is was registered on beacon chain (his deposit processed)?
> 
> probably is but still, this should be shown as an error, and `renderer.log` shows unhandled log's

Let's "resolve" this by handling 404 error
