### ISSUE TITLE
Atterstation effectivnes storage

### ISSUE THREAD

**Issue by BeroBurny** [NodeFactoryIo/ChainGuardian#504]
for some reason, UI stuck and stop storing attestations (restart resolved a problem)

[logs.zip](https://github.com/NodeFactoryIo/ChainGuardian/files/6029619/logs.zip)

![Screenshot 2021-02-23 153511](https://user-images.githubusercontent.com/6376047/108860450-7e814780-75ee-11eb-8390-fb21e8d38b0d.png)

**Comment by morrigan** [comment]
not reproducible
