### ISSUE TITLE
Beacon node page for an unsynced beacon node is a blank page

### ISSUE THREAD

**Issue by lsankar4033** [NodeFactoryIo/ChainGuardian#510]
**Describe the bug**
Clicking on Beacon node link for a not-fully-synced remote beacon node brings me to a blank page.

**To Reproduce**
1. Add a remote beacon node 
2. Click on the box for that beacon node in the 'Beacon nodes management' page

**Logs**

**Expected behavior**
I assume this would take me to a dashboard showing performance/sync status of this beacon node.

**Screenshots**
![Screen Shot 2021-03-01 at 4 32 56 PM](https://user-images.githubusercontent.com/451947/109578321-d109aa80-7aab-11eb-81ba-520aef4218fa.png)

![Screen Shot 2021-03-01 at 4 33 03 PM](https://user-images.githubusercontent.com/451947/109578329-d6ff8b80-7aab-11eb-9736-ccac09aa5092.png)

**Desktop:**
- OS: macOS
- Version: 11.2.1
- Network: Pyrmont
- Chain Guardian Version: 0.5.0

**Comment by BeroBurny** [comment]
Thank you for the report, I'm on it.
