### ISSUE TITLE
Create validator component

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/ChainGuardian#54]
figma: https://www.figma.com/file/S5odpXGtT3b0yXItCpDCXK/ChainGuardian?node-id=192%3A659

Props should be:
- stats: object
   - roi: number
   - balance: BN
   - uptime: number
- beaconNodes: array<object>
   - id: string
   - url: string
   - respTime
- onBeaconNodeClick: function
- onRemoveClick: function
- onDetailsClick: function

**Comment by irubido** [comment]
Validator component merged to master
