### ISSUE TITLE
Support Nimbus BN

### ISSUE THREAD

**Issue by morrigan** [NodeFactoryIo/ChainGuardian#551]

**Comment by mpetrunic** [comment]
nodefactory/nimbus-eth2:unstable-latest contains rest api code

**Comment by morrigan** [comment]
> nodefactory/nimbus-eth2:unstable-latest contains rest api code

I'm confused, why we have our image for that? :D

**Comment by mpetrunic** [comment]
because they don't publish unstable docker images. But it's no longer relevant, they might not release rest api soon, so I will implemet json rpc api converter (once I manage to setup testnet) and we can switch to standard api once they release
