### ISSUE TITLE
Fix UI issues

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/ChainGuardian#88]
With some changes on various containers some UI bugs apeared:
- [x] "I have saved this mnemonic" button is missing top padding
- [x] Copy button in mnemonic and copy field is aligned top
- [x] ~~When verifying mnemonic, invalid button blinks "correct" green for a second~~
- [x] center text in tool tip
- [x] text is overlapping with validation checkmark in input fields
- [x] password input isn't focused on create password screen

We can have this issue opened up and just add stuff here.

**Comment by irubido** [comment]
#91 
"When verifying mnemonic, invalid button blinks "correct" green for a second"
In Figma, verifying uses <ButtonInverted>, green blink is :active dark green color on that button.
Should that be changed to some other button instead?

**Comment by irubido** [comment]
#118

**Comment by irubido** [comment]
#124 Password Input focus
